// <auto-generated />
using System;
using MarshalApp.Net.Security.API.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarshalApp.Net.Security.API.Migrations
{
    [DbContext(typeof(SecurityContext))]
    [Migration("20220708181846_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MarshalApp.Net.Security.API.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanAccessAuthors")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAccessBooks")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAccessGrades")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAccessStudent")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddAuthor")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAddStudent")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSaveAuthor")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSaveStudent")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
